trigger:
  branches:
    include:
    - main

jobs:

- job: 'Test'
  displayName: "Test template"

  strategy:
    matrix:
      Linux-py3.10:
        imageName: 'ubuntu-20.04'
        pythonVersion: '3.10'

      macOS-py3.10:
        imageName: 'macos-10.15'
        pythonVersion: '3.10'

      Windows-py3.10:
        imageName: 'windows-2019'
        pythonVersion: '3.10'
      Windows-py3.9:
        imageName: 'windows-2019'
        pythonVersion: '3.9'
      Windows-py3.8:
        imageName: 'windows-2019'
        pythonVersion: '3.8'
      Windows-py3.7:
        imageName: 'windows-2019'
        pythonVersion: '3.7'
      Windows-py3.6:
        imageName: 'windows-2019'
        pythonVersion: '3.6'

  pool:
    vmImage: $(imageName)

  steps:

  - checkout: self
    path: ndx-template

  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(pythonVersion)'
      architecture: 'x64'

  - script: |
      python -m pip install --upgrade pip
      python -m pip install --upgrade setuptools
      python -m pip install cookiecutter "pynwb>=1.5.0" "hdmf-docutils>=0.4.4"
    displayName: 'Install build dependencies'

  - bash: |
      git config --global user.email "you@example.com"
      git config --global user.name "Your Name"
    displayName: 'Configure git'

  - bash: |
      cookiecutter -v --no-input --output-dir "$(Agent.BuildDirectory)" .
    displayName: 'Evaluate template from local source'

  - bash: |
      python tests/test_template_evaluation.py "$(Agent.BuildDirectory)/ndx-my-namespace/" "ndx-my-namespace"
    displayName: 'Check files'

  - bash: |
      cd "$(Agent.BuildDirectory)/ndx-my-namespace"
      python setup.py install
      python -m unittest src/pynwb/tests/test_tetrodeseries.py
    displayName: 'Run PyNWB test'

  - bash: |
      set -e
      cd "$(Agent.BuildDirectory)/ndx-my-namespace/docs"
      make apidoc
      make html
    displayName: 'Build documentation'
