trigger:
  branches:
    include:
    - master

parameters:
  pythonVersions: ['3.7', '3.6', '3.5'],
  operatingSystems: ['ubuntu-16.04', 'macos-10.13', 'vs2017-win2016']

jobs:

- job: 'Test'
  displayName: "Evaluate cookiecutter template"

  strategy:
    matrix:
      ${{ each py in parameters.pythonVersions }}:
        ${{ each os in parameters.operatingSystems }}:
          ${{ format('{0}{1}', py, os) }}:
            imageName: ${{ image }}
            pythonVersion: ${{ py }}

  pool:
    vmImage: $(imageName)

  steps:

  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(pythonVersion)'
      architecture: 'x64'

  - script: |
      python -m pip install --upgrade pip
      python -m pip install --upgrade setuptools
      python -m pip install cookiecutter
    displayName: 'Install build dependencies'

  - bash: |
      python -m cookiecutter --no-input --output-dir "$(Agent.BuildDirectory)" "$(Build.SourcesDirectory)"
    displayName: 'Evaluate template'


