trigger:
  branches:
    include:
    - master

jobs:

- job: 'Test'
  displayName: "Test template"

  strategy:
    matrix:
      Linux-py3.8:
        imageName: 'ubuntu-20.04'
        pythonVersion: '3.8'

      macOS-py3.8:
        imageName: 'macos-10.15'
        pythonVersion: '3.8'

      Windows-py3.8:
        imageName: 'windows-2019'
        pythonVersion: '3.8'
      Windows-py3.7:
        imageName: 'windows-2019'
        pythonVersion: '3.7'
      Windows-py3.6:
        imageName: 'windows-2019'
        pythonVersion: '3.6'

  pool:
    vmImage: $(imageName)

  steps:

  - checkout: self
    path: ndx-template

  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(pythonVersion)'
      architecture: 'x64'

  - script: |
      python -m pip install --upgrade pip
      python -m pip install --upgrade setuptools
      python -m pip install cookiecutter pynwb "hdmf-docutils>=0.4.1"
    displayName: 'Install build dependencies'

  - bash: |
      git config --global user.email "you@example.com"
      git config --global user.name "Your Name"
    displayName: 'Configure git'

  - bash: |
      cookiecutter -v --no-input --output-dir "$(Agent.BuildDirectory)" gh:nwb-extensions/ndx-template --checkout "$(System.PullRequest.SourceBranch)"
    displayName: 'Evaluate template'

  - bash: |
      python tests/test_template_evaluation.py "$(Agent.BuildDirectory)/ndx-my-namespace/" "ndx-my-namespace"
    displayName: 'Check files'

  - bash: |
      cd "$(Agent.BuildDirectory)/ndx-my-namespace"
      python setup.py install
      python -m unittest src/pynwb/tests/test_tetrodeseries.py
    displayName: 'Run PyNWB test'

  - bash: |
      set -e
      cd "$(Agent.BuildDirectory)/ndx-my-namespace/docs"
      make apidoc
      make html
    displayName: 'Build documentation'
