name: Run tests
on:
  schedule:
    - cron: '0 5 * * *'  # once per day at midnight ET
  push:
  workflow_dispatch:

jobs:
  run-tests:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-${{ matrix.name }}
      cancel-in-progress: true
    strategy:
      fail-fast: false
      matrix:
        include:
        - { name: linux-python3.9    , os: ubuntu-latest  , python-ver: "3.9"  }
        - { name: linux-python3.13   , os: ubuntu-latest  , python-ver: "3.13" }
        - { name: windows-python3.9  , os: windows-latest , python-ver: "3.9"  }
        - { name: windows-python3.13 , os: windows-latest , python-ver: "3.13" }
        - { name: macos-python3.9    , os: macos-latest   , python-ver: "3.9"  }
        - { name: macos-python3.13   , os: macos-latest   , python-ver: "3.13" }
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-ver }}

      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install cookiecutter pynwb hdmf-docutils
          python -m pip list

      - name: Configure git
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"

      - name: Run template tests
        run: |
          python -m pip install pytest pytest-cookies
          pytest tests

      - name: Evaluate template from local source
        run: |
          cookiecutter -v --no-input --output-dir ./out .

      - name: Check generated files
        run: |
          python tests/test_bake_project.py ./out/ndx-my-namespace/ ndx-my-namespace

      - name: Run PyNWB tests from generated extension
        run: |
          cd ./out/ndx-my-namespace
          python -m pip install -U ".[test]"
          pytest

      - name: Run ruff on generated extension
        run: |
          cd ./out/ndx-my-namespace
          ruff check .

      - name: Run codespell on generated extension
        run: |
          cd ./out/ndx-my-namespace
          codespell .

      - name: Build documentation from generated extension
        run: |
          set -e
          cd ./out/ndx-my-namespace/docs
          make apidoc
          make html
